"GENERATED"

load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("@rules_dotnet//dotnet:defs.bzl", "nuget_repo")
load("@rules_dotnet//dotnet/private/rules/nuget:nuget_archive.bzl", "nuget_archive")

def nativeaot_packs():
    "nativeaot_packs"
    nuget_repo(
        name = "dotnet.nativeaot_packs",
        packages = [
            # runtime.{rid}.Microsoft.DotNet.ILCompiler — ILC compiler + native SDK + MIBC
            # net8.0
            {"name": "runtime.linux-x64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.linux-x64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-Sx/I8iody93kYKFa+ffzLfgfqWeXuQrRoFGV3kh8tHIHWzxlH3EOxOvH4pj3qLkuhBJ9ErQpd0m8UrkIqQ3a2g==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-arm64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.linux-arm64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-RR2Cqc44GcwrsTMzngujcO8qZxTkaG5RGRbn8EKy67X/MUa8+wUjdRQv6ddnkxJ2PQdX/aYdkx0dpO/HOp7+Pw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-musl-x64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.linux-musl-x64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-yMAnYrJaBAwcv/gjOcEw5aW/FF7i83jf8DskHx/gtAR/zPwRo/f//dL13iyFKR7w04v7ZNXWDnz4G1dC9UTp4w==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-musl-arm64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.linux-musl-arm64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-xOjn62Y5FlWY34mLcZR5gRp4hfGu5wj/9PT+HT+CZQ6EcJ+xqhb5hiygJSjsCwqDnQCKvcr9hXElhPyUFvRWQA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.osx-x64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.osx-x64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-UOk19HsHzOH0vKwEeFOultu0RYOC2Opm2VtbQ3hBNrn1nAdObrn3FoGL1eoNIOB6q2o/XKU0SMxSFRe5Cbt7Lg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.osx-arm64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.osx-arm64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-pH8lL82nUL0YkWWznRfrKsalkrC63Oc1pTTfHWTp1UQg17HrtF5l0rLqi693h8aSH0H+/PXShfL2ZIdQKtkmRw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.win-x64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.win-x64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-dQxv1r11Ke0xWLwIFe1CglmMEqmnhLxUfGm4aNKoYWFhut85ySaUjjLNxcQ2LhC5rwDTM/PxPqlXS7FUlHZnvA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.win-arm64.microsoft.dotnet.ilcompiler.v8.0.22", "id": "runtime.win-arm64.Microsoft.DotNet.ILCompiler", "version": "8.0.22", "sha512": "sha512-NPKm0qkNvEAz/j04/KbdIx5Zye1Bbv9XnZKZYf4jDzC+q8oEDU/O9KF6Z9ifamEqarfb8k0cAxGixWKpwyefRA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            # net9.0
            {"name": "runtime.linux-x64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.linux-x64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-133VD7s2edW9CNuOJyKyc4nCM9L7yOSu9zbisBxjgtwBBKH5D2lNddIfxnZ4VkJeEDFBX/jar7d8aYHhZo8VDw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-arm64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.linux-arm64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-mp1jwpSKd+l/9/10sd/TgWwi/47U4j84Gq+opdUnVJmjdsRk+yTBokyfK7UsoENM/0htDxyZO3le7puH6DdOew==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-musl-x64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.linux-musl-x64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-8C4gsaUg4mk1bUnvLV9Ye1cXQwMLaov0YEjlGDoXdtN+GeIl6nYNZL0y8tud5zhR3BAeYJq3bDw9ItKekx1dFw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-musl-arm64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.linux-musl-arm64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-ZAJjYP0LiASdxT58mGTQ1e0NpUdw3b1sHU2sRD6m1QPf1bkz6kf+FUSWrqMNx/EF/YDPVnqiY0XdOaHlfynmUQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.osx-x64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.osx-x64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-x97FYHDTVzHVroRs+f6eoSrHExDxNyRT6qMFoq1q11Hw4acO4cb19rXHAIOAmU1dNXY0PTT/XRI3jKrtCWC7aQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.osx-arm64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.osx-arm64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-j8ZzHU0TB3z+89skZcN60YN894NUE29DedsHDLjMI5vajloZSRKWjrDNrAtRYcJQHsn/RfY/vOlirrhkG5nNmQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.win-x64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.win-x64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-ocUPwvvfud3gR584qlx8Y8Rd62xB4EdYoYMgos2ArLfA7hg7BZ9ZXY6tISQ0raabvU5azEzi9tB6QbDftqgn+g==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.win-arm64.microsoft.dotnet.ilcompiler.v9.0.11", "id": "runtime.win-arm64.Microsoft.DotNet.ILCompiler", "version": "9.0.11", "sha512": "sha512-FT+7+edjauTSsplgWPCiYyB9EGMvSd3+YVrsXeKBw3ym5ewcb3bnAaQDP/EPEjo6YPlGO6kEzZneBlhfuloqdg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            # net10.0
            {"name": "runtime.linux-x64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.linux-x64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-RfDDFGwkXvXes6pzq+Fl8RNweoSOwrQsjL++Zp1+DLY9uwAoKeDYjTai2Rin29MjmD5t854ZivDKP3X5HXYRRg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-arm64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.linux-arm64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-fKoXVn60Ct8JOazjDuwpzGZSGqVHBXboJeyCWJQj6w2B2x0p3mOJkR0/kOifxT+E2NMX2Zx12VELKK9hAAOt2w==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-musl-x64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.linux-musl-x64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-Gubgq6b9GOrD/q+eXHW14RrxcYeWsQ2bl9jL8HZaR6kXYVWd1CAF1TjKbqFLLuG01pqvDIdu8R6pMxGgsWWKFA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.linux-musl-arm64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.linux-musl-arm64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-YjvVt1y61529YYJzPuFbeFxBgekq8sDg01yudN6zKcDmacQhUtfx16xijd/9bcixH4HWCjB7tjEHLuDptm5m+Q==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.osx-x64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.osx-x64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-gbyYz6R9QJJZ5j6XtkG5asyKRcW6IvnXLwklvAvk4bkU0+kP7USIn+EtXyDqFKuiohPRzD+sHi04LmDqc+FRiA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.osx-arm64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.osx-arm64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-C2VAFhG7JYz5QEkZGkiPgoJTiERvR/bwVWfEdTyijHcUqeryjm0u89qx5Iz5AOR6U5wQNej+2Pp5BdlEd/MKPw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.win-x64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.win-x64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-XHtJ+LmFsV0RRD1H8zpRp3+yzOstV/TaRwAg38b+8PvgXn+VEIVVHzlqWu/eB8AMPoVbC7b+OnOTTlBPf3R7+g==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "runtime.win-arm64.microsoft.dotnet.ilcompiler.v10.0.0", "id": "runtime.win-arm64.Microsoft.DotNet.ILCompiler", "version": "10.0.0", "sha512": "sha512-PtkF0VBMXdPyavJUUaCp6OBEhc1SeCz7oaYTn8y+TqczP75cqDXIUk7X6DL20UorQ0VmXBAXLVHv9ey6LP8Mbg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},

            # Microsoft.NETCore.App.Runtime.NativeAOT.{rid} — managed framework DLLs + native interop libs
            # (net9.0+ only; for net8.0, the ILCompiler package contains everything)
            # net9.0
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-x64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-x64", "version": "9.0.11", "sha512": "sha512-lvLhPhBTd9zOZkk5TTbIYReet3g4HgAJdm0+y7dwlQXbawhHvU6INS1W20CDc4PH1V0wUmWw1NOySqOS61v7fQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-arm64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-arm64", "version": "9.0.11", "sha512": "sha512-4+Bw8l49UCG0zOetwdZmwKJFgaDh9tEpxQbuIQPlu7bonwmp7QS1jeR6YUq7Y+J5GWmmYOKuOpmJBg0oAkdtyQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-musl-x64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-musl-x64", "version": "9.0.11", "sha512": "sha512-pgV5nxFTvmdnLPE22T4h9yvxZ1Wf6LcJ6WphFJZ6dyxP+L8WaZ+408gjZjYRoOAzjR8pDl7aZPpD/+LSpquTbg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-musl-arm64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-musl-arm64", "version": "9.0.11", "sha512": "sha512-drGB2NAb9Rvo9ID0p0NTakMZwki7eCBLXVlerTWW4OX7O345o2Ap8tGlIADYdfmo7WkKUEVnQJ+pp5BNc7s13g==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.osx-x64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.osx-x64", "version": "9.0.11", "sha512": "sha512-2QD6w4sGgVDqWokyZlI0r/StUUAfHC4KD7W4lfzewt93eaZsKWuJZzblHGlr2V2K8LrziIcEA/UnOzGSumZKyA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.osx-arm64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.osx-arm64", "version": "9.0.11", "sha512": "sha512-AIk7XcVZOv8xq5g2YQz6sCNWaNNn9Rx33y0NWLg5+K+DMP1+6JT8KQsfj3OgV/N+qqRXgZmIQapcb3biVoeiYg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.win-x64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.win-x64", "version": "9.0.11", "sha512": "sha512-mRgpQKZJf83EwliJ946fi8AIyKJeQZlIqFmRmDb9liszxaNL40zIHV5jxQnm4k14tVQjXeDjjscwUi9avieKEA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.win-arm64.v9.0.11", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.win-arm64", "version": "9.0.11", "sha512": "sha512-00E5oAD+Jis9xxsB5jLciLyEJzezYJm0lJG8xHBN4kA+SCPb0AJdvr9lqcYgVM/CDeyKk+nSN6TMa/zWCzvEqg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            # net10.0
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-x64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-x64", "version": "10.0.0", "sha512": "sha512-DJwKMfGknpBwSQ/FiKbN3W4n0XIF/XFtwH6hxoD/2fRjqc6GZbOnoB/qfK5VOpgnIIMpZuCb599ftPtiO8aLog==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-arm64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-arm64", "version": "10.0.0", "sha512": "sha512-Q2eKWNI659wTKYT/WntFSeA6DtTQLoFFOtn4EfVEug5oDxnJKwXfylptcw2cXF1UHmbnr3fjn41fmHF+lJ32Rw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-musl-x64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-musl-x64", "version": "10.0.0", "sha512": "sha512-4ar4h4IHFuZXo4uDArhDRWG10/M4rNLLkilexfEDVHiDxsWKdQKn3brLAU5QDbk6zAr2u7xwWyQ8toZLA3jQ9w==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.linux-musl-arm64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.linux-musl-arm64", "version": "10.0.0", "sha512": "sha512-WwVSD1gSgf73RE6tHGuoD5kDMqmYd5mIu6B3Ay2jO8MgejtfRO1qNoa6EHcq0ouVS3EIDRO/oi4lWtgzHqLHdg==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.osx-x64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.osx-x64", "version": "10.0.0", "sha512": "sha512-JCrbiueBGasaUfvwTiKKj/4pzWzdp30vIzOYcUmbfCX8jtR40Ey8aHtt3P+LFKKeZJAOpOOv22gk0B48P7Ah7A==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.osx-arm64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.osx-arm64", "version": "10.0.0", "sha512": "sha512-MNtC4Vnbgwmb8KFfsdp+Xu4yQghA/cOjXYRBx0Imk+2xPgBkWExCFwbtyX3g/t4dYf8VR/uXGJc6/FFTMhcgvQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.win-x64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.win-x64", "version": "10.0.0", "sha512": "sha512-W0TkFiCX18X42x/7yLigJz4dFJypJshxdjAkSdOBC7UIN10EIqecXuid8/xXF/GHfn5T01o5W7OXlDm5RTXodA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "microsoft.netcore.app.runtime.nativeaot.win-arm64.v10.0.0", "id": "Microsoft.NETCore.App.Runtime.NativeAOT.win-arm64", "version": "10.0.0", "sha512": "sha512-pBU/rw1TcVxKoLctkrHcWpGHVi61ZMJwaFXTWRO5Wayp3EVu6buWTXew8PmgFnVwqw9GvCBiqTvCeabTh2kVgA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
        ],
    )

    # ILLink analyzers — Roslyn analyzers for AOT/trim compatibility warnings.
    # These are TFM-matched: use the version corresponding to the target framework.
    maybe(
        nuget_archive,
        name = "nuget.microsoft.net.illink.tasks.v8.0.22",
        id = "microsoft.net.illink.tasks",
        version = "8.0.22",
        sha512 = "sha512-iYmOLnweVM6lBYOPad9V+6jshSD3SW+OTebTEo3o3sFuvQMjxyj8c9JfjUStrWbZJZoqqMwt8y23ePFdImtahg==",
        sources = ["https://api.nuget.org/v3/index.json"],
    )
    maybe(
        nuget_archive,
        name = "nuget.microsoft.net.illink.tasks.v9.0.11",
        id = "microsoft.net.illink.tasks",
        version = "9.0.11",
        sha512 = "sha512-agNcCSp6KndtdjAKzC7uBkZRLQuVjPKLoa8lgnWE61QLnthODtIN3ylyIpG/Ds+lUg37NBcIXC6gQdu7E6/VAA==",
        sources = ["https://api.nuget.org/v3/index.json"],
    )
    maybe(
        nuget_archive,
        name = "nuget.microsoft.net.illink.tasks.v10.0.0",
        id = "microsoft.net.illink.tasks",
        version = "10.0.0",
        sha512 = "sha512-nmdgBAyTi4gyuP18U9I7JhVSC31+mZyyQQzmldKxkaVQCB5mcPjgvnfkJCQjN84VRFE++hXW0xBqPSbUuny0QQ==",
        sources = ["https://api.nuget.org/v3/index.json"],
    )
