"GENERATED BY SDK GENERATOR"

nativeaot_pack_lookup_table = {
    "net8.0": {
        "linux-x64": "//dotnet/private/sdk/nativeaot_packs:net8.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/nativeaot_packs:net8.0_linux-arm64",
        "linux-musl-x64": "//dotnet/private/sdk/nativeaot_packs:net8.0_linux-musl-x64",
        "linux-musl-arm64": "//dotnet/private/sdk/nativeaot_packs:net8.0_linux-musl-arm64",
        "osx-x64": "//dotnet/private/sdk/nativeaot_packs:net8.0_osx-x64",
        "osx-arm64": "//dotnet/private/sdk/nativeaot_packs:net8.0_osx-arm64",
        "win-x64": "//dotnet/private/sdk/nativeaot_packs:net8.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/nativeaot_packs:net8.0_win-arm64",
    },
    "net9.0": {
        "linux-x64": "//dotnet/private/sdk/nativeaot_packs:net9.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/nativeaot_packs:net9.0_linux-arm64",
        "linux-musl-x64": "//dotnet/private/sdk/nativeaot_packs:net9.0_linux-musl-x64",
        "linux-musl-arm64": "//dotnet/private/sdk/nativeaot_packs:net9.0_linux-musl-arm64",
        "osx-x64": "//dotnet/private/sdk/nativeaot_packs:net9.0_osx-x64",
        "osx-arm64": "//dotnet/private/sdk/nativeaot_packs:net9.0_osx-arm64",
        "win-x64": "//dotnet/private/sdk/nativeaot_packs:net9.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/nativeaot_packs:net9.0_win-arm64",
    },
    "net10.0": {
        "linux-x64": "//dotnet/private/sdk/nativeaot_packs:net10.0_linux-x64",
        "linux-arm64": "//dotnet/private/sdk/nativeaot_packs:net10.0_linux-arm64",
        "linux-musl-x64": "//dotnet/private/sdk/nativeaot_packs:net10.0_linux-musl-x64",
        "linux-musl-arm64": "//dotnet/private/sdk/nativeaot_packs:net10.0_linux-musl-arm64",
        "osx-x64": "//dotnet/private/sdk/nativeaot_packs:net10.0_osx-x64",
        "osx-arm64": "//dotnet/private/sdk/nativeaot_packs:net10.0_osx-arm64",
        "win-x64": "//dotnet/private/sdk/nativeaot_packs:net10.0_win-x64",
        "win-arm64": "//dotnet/private/sdk/nativeaot_packs:net10.0_win-arm64",
    },
}
